#Docker Compose Code
version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: dhaoujawhar/alpine:2.1-SE2
    ports: 8086:8089
    mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
