version: "3"

services:
  springboot-app:
   # container_name: Kaddem-app
    image: jediditasnim/alpine:0.1-SPRING-Compose
    restart: always
    build: .
    ports:
      - 8147:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/User/DESKTOP/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
       MYSQL_DATABASE: test
       MYSQL_ROOT_PASSWORD: root

  angular-app:
    image:  jediditasnim/alpine:0.1-Angular
    build: .
    ports:
      - "8001:80"





