version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jediditasnim/alpine
    container_name: Kaddem
    restart: always
    ports:
      - "8089:8089"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
   


volumes:
    db:


