version: "3"

services:
  springboot-app:
    container_name: Kaddem-app
    image: jediditasnim/alpine:0.1-SPRING-DockerCompose
    restart: always
    build: .
    ports:
      - 8000-8999:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/Users/User/Desktop/DEVOPS/Projet/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE= test
      - MYSQL_ALLOW_EMPTY_PASSWORD= root





