version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: dhaoujawhar/alpine:3.0-SPRING
    restart: always
    build: .
    ports:
      - 8066:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root