version: "3.3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    image: jediditasnim/alpine
    container_name: Kaddem
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306,
      "spring.datasource.username" : "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect"
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
    db:


