version: "3"
services:
  springboot-app:
    #container_name: spring-app
    image: hanen/alpine
    build: .
    ports:
      - 8000-8999:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

