# Utilisez une image de base avec Java
FROM openjdk:11-jre-slim

# Copiez le jar de l'application dans l'image
COPY target/nom-de-votre-application.jar /app.jar

# Définissez le port sur lequel l'application va écouter
EXPOSE 8080

# Commande pour exécuter l'application lors du démarrage du conteneur
CMD ["java", "-jar", "/app.jar"]