version: "3"
services:
  springboot-app:
    container_name: kaddem-app
    image: hanenhammouda/alpine:2.1-SPRING-COMPOSE
    restart: always
    build: .
    ports:
       - 8023:8089
     # - 8000-8999:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/5SE2/DEVOPS/Projet/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
