version: "3"
services:
  springboot-app:
    image: eyatizaoui/alpine:1.0.0
    restart: always
    build: .
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root
