version: "3"
services:
  springboot-app:
    image: houcem1307/kaddem_back-end:2.0.0
    restart: always
    ports:
      - 8066:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  # Leave this empty for no password
    networks:
      - mynetwork  # Ensure both services are on the same network

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    volumes:
      - /home/Kaddem/DevopsProject/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD:  # Leave this empty for no password
    networks:
      - mynetwork  # Ensure both services are on the same network

networks:
  mynetwork:
