version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: hazem0419/alpine:0.0.1-SPRING
    restart: always
    ports:
      - 8088:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/Kaddem/DevopsProject/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD: root
